version: "3.8"

services:
  elasticsearch:
    build:
      context: .
      args:
        ES_VERSION: ${ES_VERSION}
    restart: on-failure
    ports:
      - "9200:9200"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        hard: -1
        soft: -1
    environment:
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      xpack.security.enabled: "true"
    networks:
      - elastic
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
